# scripts to run before `bun run`-ing a file or script
# register plugins by adding them to this list
# preload = ["./instrumentation.ts"]

logLevel = "debug" # "debug" | "warn" | "error"

[define]
# Replace any usage of "process.env.bagel" with the string `lox`.
# The values are parsed as JSON, except single-quoted strings are supported and `'undefined'` becomes `undefined` in JS.
# This will probably change in a future release to be just regular TOML instead. It is a holdover from the CLI argument parsing.
#"process.env.TZ" = "'Europe/Amsterdam'"
